multicamera: 
  device_info:
    name: realsense_camera
    uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
    user_description: Realsense Multicamera Interface
    manufacturer:
      name: Microsoft
      uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
      
    model:
      name: realsense
      uuid: f965f965-f965-f965-f965-f965f965f965
    
    serial_number: 123456789
      
    update_frequency: 30

    pose:
      frame:
        name: realsense_camera
        uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
      orientation:
        w: 0.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: 0.0
        y: 0.0
        z: 0.0
    
    device_classes:
      - class_identifier:
          name: multicamera
          uuid: 39b539b5-39b5-39b5-39b5-39b539b539b5
        subclasses:
          - camera
          - infrared
          - depth_sensor
          - body_overlay
    implemented_types:
      - com.robotraconteur.imaging.MultiCamera
        
  cameras:    
    - camera: 
      name: realsense_color_camera
      user_description: Realsense Color Camera Interface
      parent_device:
        name: realsense_multicamera
        uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
      device_classes:
        - class_identifier:
            name: camera
            uuid: 39b539b5-39b5-39b5-39b5-39b539b539b5
          
            
      implemented_types:
        - com.robotraconteur.imaging.Camera
            
      camera_calibration:
        image_size:
          width: 640
          height: 480
        
        K:
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0

    
  
    - camera: 
      name: realsense_infrared_camera
      user_description: Realsense Infrared Camera Interface
      parent_device:
        name: realsense_multicamera
        uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
      device_classes:
        - class_identifier:
            name: infrared
            uuid: 39b539b5-39b5-39b5-39b5-39b539b539b5
          
            
      implemented_types:
        - com.robotraconteur.imaging.Camera
            
      camera_calibration:
        image_size:
          width: 640
          height: 480
        K:
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0


  
    - camera:
      name: realsense_depth_camera
      user_description: Realsense Depth Camera Interface
      parent_device:
        name: realsense_multicamera
        uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
      device_classes:
        - class_identifier:
            name: depth_sensor
            uuid: 39b539b5-39b5-39b5-39b5-39b539b539b5
          
            
      implemented_types:
        - com.robotraconteur.imaging.Camera
            
    
      camera_calibration:
        image_size:
          width: 640
          height: 480
        K:
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0
          -0.0


point_cloud:
  device_info:
    name: realsense_pointcloud
    user_description: Realsense Point Cloud Generator
    parent_device: 
      name: realsense_multicamera
      uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
    manufacturer:
      name: Microsoft
      uuid: 82d282d2-82d2-82d2-82d2-82d282d282d2
    model:
      name: realsense
      uuid: f965f965-f965-f965-f965-f965f965f965
    
    serial_number: 123456789
      
    update_frequency: 30

    pose:
      orientation:
        w: 0.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: 0.0
        y: 0.0
        z: 0.0
    device_classes:
      - class_identifier:
          name: pointcloud
          uuid: 39b539b5-39b5-39b5-39b5-39b539b539b5
        subclasses:
          -point_cloud_sensor
    implemented_types:
      - com.robotraconteur.pointcloud.sensor.PointCloudSensor
  sensor_type: point_cloud
  range_min:
    x: 0.0
    y: 0.0
    z: 0.3
  range_max:
    x: 0.0
    y: 0.0
    z: 10.0
  
  resolution:
    x: 0.0
    y: 0.0
    z: 0.0